export const CERTIFICATES = [
  {
    id: "1",
    certificateId: "CPCCU-2026-001",
    recipientName: "Arif Hossain",
    recipientId: "CSE-2021-101",
    contestName: "Code Breeze and Freeze - 3",
    contestType: "programming-contest",
    certificateType: "winner",
    rank: 1,
    issueDate: "2026-02-15",
    issuedBy: "CPCCU - City University",
    description:
      "Awarded for achieving 1st position in the Code Breeze and Freeze - 3 Programming Contest.",
  },
  {
    id: "2",
    certificateId: "CPCCU-2026-002",
    recipientName: "Nusrat Jahan",
    recipientId: "CSE-2021-205",
    contestName: "Code Breeze and Freeze - 3",
    contestType: "programming-contest",
    certificateType: "runner-up",
    rank: 2,
    issueDate: "2026-02-15",
    issuedBy: "CPCCU - City University",
    description:
      "Awarded for achieving 2nd position in the Code Breeze and Freeze - 3 Programming Contest.",
  },
  {
    id: "3",
    certificateId: "CPCCU-2026-003",
    recipientName: "Tanvir Ahmed",
    recipientId: "CSE-2022-312",
    contestName: "Code Breeze and Freeze - 3",
    contestType: "programming-contest",
    certificateType: "top-performer",
    rank: 3,
    issueDate: "2026-02-15",
    issuedBy: "CPCCU - City University",
    description:
      "Awarded for achieving 3rd position in the Code Breeze and Freeze - 3 Programming Contest.",
  },
  {
    id: "4",
    certificateId: "CPCCU-2026-004",
    recipientName: "Sadia Islam",
    recipientId: "CSE-2022-418",
    contestName: "Code Breeze and Freeze - 3",
    contestType: "programming-contest",
    certificateType: "participation",
    issueDate: "2026-02-15",
    issuedBy: "CPCCU - City University",
    description:
      "Awarded for participating in the Code Breeze and Freeze - 3 Programming Contest.",
  },
  {
    id: "5",
    certificateId: "CPCCU-2026-005",
    recipientName: "Rakibul Hasan",
    recipientId: "CSE-2020-089",
    contestName: "Beyond the Code: Article Writing Contest 2026",
    contestType: "article-writing",
    certificateType: "winner",
    rank: 1,
    issueDate: "2026-03-01",
    issuedBy: "CPCCU - City University",
    description:
      "Awarded for winning the Beyond the Code: Article Writing Contest 2026.",
  },
  {
    id: "6",
    certificateId: "CPCCU-2025-101",
    recipientName: "Mehedi Hassan",
    recipientId: "CSE-2022-120",
    contestName: "Beat the Vibe Programming Contest",
    contestType: "programming-contest",
    certificateType: "winner",
    rank: 1,
    issueDate: "2025-11-10",
    issuedBy: "CPCCU - City University",
    description:
      "Awarded for achieving 1st position in the Beat the Vibe Programming Contest.",
  },
  {
    id: "7",
    certificateId: "CPCCU-2025-102",
    recipientName: "Fatema Akter",
    recipientId: "CSE-2021-334",
    contestName: "Code Queens Challenge",
    contestType: "programming-contest",
    certificateType: "winner",
    rank: 1,
    issueDate: "2025-08-20",
    issuedBy: "CPCCU - City University",
    description:
      "Awarded for achieving 1st position in the Code Queens Challenge.",
  },
  {
    id: "8",
    certificateId: "CPCCU-2024-201",
    recipientName: "Imran Khan",
    recipientId: "CSE-2023-045",
    contestName: "Console Craze Hackathon",
    contestType: "hackathon",
    certificateType: "winner",
    rank: 1,
    issueDate: "2024-07-15",
    issuedBy: "CPCCU - City University",
    description:
      "Awarded for winning the Console Craze Hackathon with the most innovative console application.",
  },
  {
    id: "9",
    certificateId: "CPCCU-2024-202",
    recipientName: "Shamim Ahsan",
    recipientId: "CSE-2023-067",
    contestName: "Console App Workshop",
    contestType: "workshop",
    certificateType: "participation",
    issueDate: "2024-07-09",
    issuedBy: "CPCCU - City University",
    description:
      "Awarded for successfully completing the Console App Workshop on C/C++ programming.",
  },
  {
    id: "10",
    certificateId: "CPCCU-2024-203",
    recipientName: "Riya Chowdhury",
    recipientId: "CSE-2022-278",
    contestName: "Flash Contest - 2024",
    contestType: "programming-contest",
    certificateType: "top-performer",
    rank: 3,
    issueDate: "2024-09-05",
    issuedBy: "CPCCU - City University",
    description:
      "Awarded for achieving 3rd position in the Flash Contest - 2024.",
  },
  {
    id: "11",
    certificateId: "CPCCU-2024-204",
    recipientName: "Alamin Hossain",
    recipientId: "CSE-2021-156",
    contestName: "ICPC Regional Prep Contest - 2024",
    contestType: "programming-contest",
    certificateType: "participation",
    issueDate: "2024-10-20",
    issuedBy: "CPCCU - City University",
    description:
      "Awarded for participating in the ICPC Regional Prep Contest - 2024.",
  },
  {
    id: "12",
    certificateId: "CPCCU-2024-205",
    recipientName: "Sumaiya Begum",
    recipientId: "CSE-2023-190",
    contestName: "Code Clash - 2024",
    contestType: "programming-contest",
    certificateType: "runner-up",
    rank: 2,
    issueDate: "2024-12-01",
    issuedBy: "CPCCU - City University",
    description: "Awarded for achieving 2nd position in Code Clash - 2024.",
  },
];

export const CONTEST_NAMES = [
  "All Contests",
  "Code Breeze and Freeze - 3",
  "Beyond the Code: Article Writing Contest 2026",
  "Beat the Vibe Programming Contest",
  "Code Queens Challenge",
  "Console Craze Hackathon",
  "Console App Workshop",
  "Flash Contest - 2024",
  "ICPC Regional Prep Contest - 2024",
  "Code Clash - 2024",
  "Ctrl+Alt+Defeat Programming Contest",
  "Eid Code Fest CPCCU: 2024",
];

