// ===== Dashboard Stats =====
export const dashboardStats = {
    totalMembers: 248,
    activeEvents: 5,
    totalPosts: 64,
    pendingProfiles: 3,
    memberGrowth: 12.5,
    eventAttendance: 89,
    postEngagement: 34.2,
    approvedProfiles: 4,
    unreadMessages: 5,
};
// ===== Chart Data =====
export const memberGrowthData = [
    { name: 'Jan', value: 180, secondary: 45 },
    { name: 'Feb', value: 195, secondary: 52 },
    { name: 'Mar', value: 205, secondary: 48 },
    { name: 'Apr', value: 218, secondary: 61 },
    { name: 'May', value: 230, secondary: 55 },
    { name: 'Jun', value: 248, secondary: 67 },
];
export const eventAttendanceData = [
    { name: 'Workshops', value: 85 },
    { name: 'Seminars', value: 72 },
    { name: 'Hackathons', value: 95 },
    { name: 'Meetups', value: 60 },
    { name: 'Competitions', value: 78 },
];
export const postCategoryData = [
    { name: 'Announcements', value: 18 },
    { name: 'Blog', value: 22 },
    { name: 'Tutorials', value: 14 },
    { name: 'News', value: 10 },
];
// ===== Posts Data =====
export const demoPosts = [
    {
        id: 'p1',
        title: 'Annual Hackathon 2026 Registration Open',
        slug: 'annual-hackathon-2026',
        content: 'We are excited to announce that registration for the Annual CPCCU Hackathon 2026 is now open...',
        excerpt: 'Registration for the Annual CPCCU Hackathon 2026 is now open. Sign up before slots run out!',
        author: 'Ananya Sharma',
        category: 'announcement',
        status: 'published',
        tags: ['hackathon', 'competition', '2026'],
        createdAt: '2026-02-15T10:00:00Z',
        updatedAt: '2026-02-15T10:00:00Z',
        views: 342,
    },
    {
        id: 'p2',
        title: 'Introduction to Competitive Programming',
        slug: 'intro-competitive-programming',
        content: 'A comprehensive guide to getting started with competitive programming...',
        excerpt: 'Learn the fundamentals of competitive programming and ace your next coding contest.',
        author: 'Raj Patel',
        category: 'tutorial',
        status: 'published',
        tags: ['competitive-programming', 'tutorial', 'beginner'],
        createdAt: '2026-02-10T08:30:00Z',
        updatedAt: '2026-02-12T14:20:00Z',
        views: 528,
    },
    {
        id: 'p3',
        title: 'CPCCU Wins Inter-University Code Championship',
        slug: 'cpccu-wins-championship',
        content: 'Our team secured first place at the Inter-University Code Championship...',
        excerpt: 'CPCCU team secures first place at the Inter-University Code Championship held at DTU.',
        author: 'Priya Gupta',
        category: 'news',
        status: 'published',
        tags: ['achievement', 'competition', 'news'],
        createdAt: '2026-02-05T16:00:00Z',
        updatedAt: '2026-02-05T16:00:00Z',
        views: 891,
    },
    {
        id: 'p4',
        title: 'Understanding Graph Algorithms',
        slug: 'understanding-graph-algorithms',
        content: 'Deep dive into graph algorithms including BFS, DFS, Dijkstra and more...',
        excerpt: 'A deep dive into essential graph algorithms every programmer should know.',
        author: 'Vikram Singh',
        category: 'tutorial',
        status: 'draft',
        tags: ['algorithms', 'graphs', 'tutorial'],
        createdAt: '2026-02-18T11:00:00Z',
        updatedAt: '2026-02-20T09:00:00Z',
        views: 0,
    },
    {
        id: 'p5',
        title: 'New Club Room Allocated',
        slug: 'new-club-room-allocated',
        content: 'We are happy to announce that we have been allocated a dedicated club room...',
        excerpt: 'CPCCU has been allocated a dedicated club room in Block C, Room 302.',
        author: 'Ananya Sharma',
        category: 'announcement',
        status: 'published',
        tags: ['announcement', 'facility'],
        createdAt: '2026-01-28T10:00:00Z',
        updatedAt: '2026-01-28T10:00:00Z',
        views: 215,
    },
    {
        id: 'p6',
        title: 'Weekly DSA Practice Sessions',
        slug: 'weekly-dsa-sessions',
        content: 'Starting this month, we will conduct weekly DSA practice sessions...',
        excerpt: 'Join our weekly DSA practice sessions every Saturday from 4 PM to 6 PM.',
        author: 'Raj Patel',
        category: 'blog',
        status: 'published',
        tags: ['dsa', 'practice', 'weekly'],
        createdAt: '2026-02-01T08:00:00Z',
        updatedAt: '2026-02-01T08:00:00Z',
        views: 178,
    },
    {
        id: 'p7',
        title: 'React & Next.js Workshop Recap',
        slug: 'react-nextjs-workshop-recap',
        content: 'A recap of our successful React and Next.js workshop held last weekend...',
        excerpt: 'Missed the React and Next.js workshop? Here is a complete recap with resources.',
        author: 'Meera Kapoor',
        category: 'blog',
        status: 'archived',
        tags: ['workshop', 'react', 'nextjs'],
        createdAt: '2026-01-20T14:00:00Z',
        updatedAt: '2026-01-22T10:00:00Z',
        views: 423,
    },
];
// ===== Members Data =====
export const demoMembers = [
    {
        id: 'm1',
        name: 'Ananya Sharma',
        email: 'ananya@cpccu.club',
        avatar: '',
        role: 'admin',
        status: 'active',
        department: 'Computer Science',
        joinedAt: '2024-08-15T10:00:00Z',
        phone: '+91 98765 43210',
        skills: ['Python', 'Machine Learning', 'Web Dev'],
    },
    {
        id: 'm2',
        name: 'Raj Patel',
        email: 'raj@cpccu.club',
        avatar: '',
        role: 'moderator',
        status: 'active',
        department: 'Information Technology',
        joinedAt: '2024-09-01T10:00:00Z',
        phone: '+91 98765 43211',
        skills: ['C++', 'Competitive Programming', 'Algorithms'],
    },
    {
        id: 'm3',
        name: 'Priya Gupta',
        email: 'priya@cpccu.club',
        avatar: '',
        role: 'moderator',
        status: 'active',
        department: 'Computer Science',
        joinedAt: '2024-09-15T10:00:00Z',
        phone: '+91 98765 43212',
        skills: ['Java', 'Android Dev', 'Cloud Computing'],
    },
    {
        id: 'm4',
        name: 'Vikram Singh',
        email: 'vikram@cpccu.club',
        avatar: '',
        role: 'member',
        status: 'active',
        department: 'ECE',
        joinedAt: '2025-01-10T10:00:00Z',
        phone: '+91 98765 43213',
        skills: ['Python', 'Data Science', 'IoT'],
    },
    {
        id: 'm5',
        name: 'Meera Kapoor',
        email: 'meera@cpccu.club',
        avatar: '',
        role: 'member',
        status: 'active',
        department: 'Computer Science',
        joinedAt: '2025-02-20T10:00:00Z',
        phone: '+91 98765 43214',
        skills: ['React', 'Next.js', 'TypeScript'],
    },
    {
        id: 'm6',
        name: 'Arjun Nair',
        email: 'arjun@cpccu.club',
        avatar: '',
        role: 'member',
        status: 'pending',
        department: 'Mathematics',
        joinedAt: '2026-02-01T10:00:00Z',
        phone: '+91 98765 43215',
        skills: ['Python', 'Statistics', 'Machine Learning'],
    },
    {
        id: 'm7',
        name: 'Sanya Mehta',
        email: 'sanya@cpccu.club',
        avatar: '',
        role: 'member',
        status: 'inactive',
        department: 'Information Technology',
        joinedAt: '2024-10-05T10:00:00Z',
        phone: '+91 98765 43216',
        skills: ['JavaScript', 'Node.js', 'MongoDB'],
    },
    {
        id: 'm8',
        name: 'Dev Chauhan',
        email: 'dev@cpccu.club',
        avatar: '',
        role: 'member',
        status: 'active',
        department: 'Computer Science',
        joinedAt: '2025-06-15T10:00:00Z',
        phone: '+91 98765 43217',
        skills: ['Rust', 'Systems Programming', 'Blockchain'],
    },
];
// ===== Events Data =====
export const demoEvents = [
    {
        id: 'e1',
        title: 'Annual Hackathon 2026',
        description: 'A 48-hour hackathon focused on building innovative solutions for social good.',
        date: '2026-03-15T09:00:00Z',
        endDate: '2026-03-17T09:00:00Z',
        location: 'Main Auditorium, Block A',
        type: 'hackathon',
        status: 'upcoming',
        capacity: 200,
        registered: 156,
        organizer: 'Ananya Sharma',
        image: '',
    },
    {
        id: 'e2',
        title: 'React Advanced Patterns Workshop',
        description: 'Learn advanced React patterns including compound components, render props, and hooks.',
        date: '2026-03-05T14:00:00Z',
        endDate: '2026-03-05T18:00:00Z',
        location: 'Lab 201, Block B',
        type: 'workshop',
        status: 'upcoming',
        capacity: 50,
        registered: 42,
        organizer: 'Meera Kapoor',
        image: '',
    },
    {
        id: 'e3',
        title: 'AI & Machine Learning Seminar',
        description: 'Industry experts discuss the latest trends in AI and ML applications.',
        date: '2026-02-28T10:00:00Z',
        endDate: '2026-02-28T13:00:00Z',
        location: 'Seminar Hall 1',
        type: 'seminar',
        status: 'ongoing',
        capacity: 100,
        registered: 89,
        organizer: 'Vikram Singh',
        image: '',
    },
    {
        id: 'e4',
        title: 'Weekly Coding Meetup',
        description: 'Weekly meetup to discuss problems, share solutions, and network.',
        date: '2026-02-22T16:00:00Z',
        endDate: '2026-02-22T18:00:00Z',
        location: 'Club Room, Block C-302',
        type: 'meetup',
        status: 'completed',
        capacity: 30,
        registered: 28,
        organizer: 'Raj Patel',
        image: '',
    },
    {
        id: 'e5',
        title: 'Inter-College Programming Contest',
        description: 'Compete against teams from other colleges in this exciting programming contest.',
        date: '2026-04-10T09:00:00Z',
        endDate: '2026-04-10T17:00:00Z',
        location: 'Computer Lab Complex',
        type: 'competition',
        status: 'upcoming',
        capacity: 150,
        registered: 78,
        organizer: 'Priya Gupta',
        image: '',
    },
    {
        id: 'e6',
        title: 'Git & GitHub Workshop',
        description: 'Learn version control with Git and collaboration with GitHub.',
        date: '2026-01-25T14:00:00Z',
        endDate: '2026-01-25T17:00:00Z',
        location: 'Lab 105, Block B',
        type: 'workshop',
        status: 'completed',
        capacity: 40,
        registered: 40,
        organizer: 'Dev Chauhan',
        image: '',
    },
];
// ===== Gallery Data =====
export const demoGallery = [
    {
        id: 'g1',
        title: 'Hackathon 2025 Winners',
        description: 'The winning team celebrating their victory at the Annual Hackathon 2025.',
        imageUrl: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=400&h=300&fit=crop',
        category: 'competitions',
        uploadedBy: 'Ananya Sharma',
        uploadedAt: '2025-12-20T10:00:00Z',
        featured: true,
    },
    {
        id: 'g2',
        title: 'React Workshop Session',
        description: 'Students learning React fundamentals in our hands-on workshop.',
        imageUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=400&h=300&fit=crop',
        category: 'workshops',
        uploadedBy: 'Meera Kapoor',
        uploadedAt: '2026-01-15T14:00:00Z',
        featured: false,
    },
    {
        id: 'g3',
        title: 'Team Photo 2026',
        description: 'The core team of CPCCU for the academic year 2025-26.',
        imageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=400&h=300&fit=crop',
        category: 'team',
        uploadedBy: 'Priya Gupta',
        uploadedAt: '2026-02-01T10:00:00Z',
        featured: true,
    },
    {
        id: 'g4',
        title: 'Freshers Welcome Event',
        description: 'Welcoming new members to the club with fun activities and networking.',
        imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=300&fit=crop',
        category: 'events',
        uploadedBy: 'Raj Patel',
        uploadedAt: '2025-09-10T16:00:00Z',
        featured: false,
    },
    {
        id: 'g5',
        title: 'Code Championship Trophy',
        description: 'The trophy won at the Inter-University Code Championship.',
        imageUrl: 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=400&h=300&fit=crop',
        category: 'competitions',
        uploadedBy: 'Priya Gupta',
        uploadedAt: '2026-02-06T10:00:00Z',
        featured: true,
    },
    {
        id: 'g6',
        title: 'DSA Study Group',
        description: 'Weekly DSA study group session in the club room.',
        imageUrl: 'https://images.unsplash.com/photo-1515378960530-7c0da6231fb1?w=400&h=300&fit=crop',
        category: 'workshops',
        uploadedBy: 'Vikram Singh',
        uploadedAt: '2026-02-15T16:00:00Z',
        featured: false,
    },
];
// ===== Developer Profiles Data =====
export const demoProfiles = [
    {
        id: 'dp1',
        name: 'Anisur Rahman Farazi',
        title: 'Full Stack Engineer',
        email: 'anisurrahmanfarazi@gmail.com',
        phone: '+8801641088544',
        photoUrl: '/images/profiles/profile-2.jpg',
        githubUrl: 'https://github.com/anisurfarazi',
        linkedinUrl: 'https://linkedin.com/in/anisurfarazi',
        portfolioUrl: 'https://anisurfarazi.dev',
        skills: [
            { name: 'HTML & CSS', description: '2+ years crafting responsive, accessible layouts.' },
            { name: 'Django', description: 'Built and maintained APIs and admin panels with DRF.' },
            { name: 'PostgreSQL', description: 'Designed normalized schemas and optimized queries.' },
            { name: 'Redis', description: 'Used for caching and background task queues.' },
            { name: 'Docker', description: 'Containerized services and managed dev/prod environments.' },
        ],
        status: 'approved',
        submittedAt: '2026-01-10T10:00:00Z',
        memberSince: '2023-11-22T00:00:00Z',
        department: 'Computer Science',
    },
    {
        id: 'dp2',
        name: 'Meera Kapoor',
        title: 'Frontend Developer',
        email: 'meera.kapoor@gmail.com',
        phone: '+91 98765 43214',
        photoUrl: '/images/profiles/profile-1.jpg',
        githubUrl: 'https://github.com/meerakapoor',
        linkedinUrl: 'https://linkedin.com/in/meerakapoor',
        portfolioUrl: 'https://meerakapoor.design',
        skills: [
            { name: 'React', description: '3 years building SPAs with hooks, context, and state management.' },
            { name: 'Next.js', description: 'SSR/SSG apps with App Router, server actions, and caching.' },
            { name: 'TypeScript', description: 'Type-safe development across frontend and backend.' },
            { name: 'Tailwind CSS', description: 'Utility-first styling for rapid, responsive UIs.' },
        ],
        status: 'approved',
        submittedAt: '2026-01-15T14:00:00Z',
        memberSince: '2025-02-20T00:00:00Z',
        department: 'Computer Science',
    },
    {
        id: 'dp3',
        name: 'Raj Patel',
        title: 'Competitive Programmer & Backend Dev',
        email: 'raj.patel@gmail.com',
        phone: '+91 98765 43211',
        photoUrl: '/images/profiles/profile-4.jpg',
        githubUrl: 'https://github.com/rajpatel',
        linkedinUrl: 'https://linkedin.com/in/rajpatel',
        skills: [
            { name: 'C++', description: 'Expert-level competitive programming with STL and templates.' },
            { name: 'Algorithms', description: 'Graph theory, DP, segment trees, and advanced data structures.' },
            { name: 'Python', description: 'Scripting, automation, and backend REST APIs.' },
            { name: 'Node.js', description: 'Express and Fastify based microservices.' },
        ],
        status: 'pending',
        submittedAt: '2026-02-20T10:00:00Z',
        memberSince: '2024-09-01T00:00:00Z',
        department: 'Information Technology',
    },
    {
        id: 'dp4',
        name: 'Priya Gupta',
        title: 'Cloud & Mobile Developer',
        email: 'priya.gupta@gmail.com',
        phone: '+91 98765 43212',
        photoUrl: '/images/profiles/profile-3.jpg',
        githubUrl: 'https://github.com/priyagupta',
        linkedinUrl: 'https://linkedin.com/in/priyagupta',
        skills: [
            { name: 'Java', description: 'Android development and enterprise backend services.' },
            { name: 'Kotlin', description: 'Modern Android app development with Jetpack Compose.' },
            { name: 'AWS', description: 'EC2, S3, Lambda, and CloudFormation for scalable infra.' },
            { name: 'Firebase', description: 'Real-time databases, auth, and push notifications.' },
        ],
        status: 'pending',
        submittedAt: '2026-02-22T16:00:00Z',
        memberSince: '2024-09-15T00:00:00Z',
        department: 'Computer Science',
    },
    {
        id: 'dp5',
        name: 'Vikram Singh',
        title: 'Data Scientist & ML Engineer',
        email: 'vikram.singh@gmail.com',
        phone: '+91 98765 43213',
        photoUrl: '/images/profiles/profile-6.jpg',
        githubUrl: 'https://github.com/vikramsingh',
        linkedinUrl: 'https://linkedin.com/in/vikramsingh',
        skills: [
            { name: 'Python', description: 'NumPy, Pandas, and Scikit-learn for data analysis.' },
            { name: 'TensorFlow', description: 'Deep learning models for NLP and computer vision.' },
            { name: 'SQL', description: 'Complex queries, joins, and database optimization.' },
            { name: 'IoT', description: 'Raspberry Pi and Arduino sensor data pipelines.' },
        ],
        status: 'approved',
        submittedAt: '2026-01-05T10:00:00Z',
        memberSince: '2025-01-10T00:00:00Z',
        department: 'ECE',
    },
    {
        id: 'dp6',
        name: 'Dev Chauhan',
        title: 'Systems Programmer',
        email: 'dev.chauhan@gmail.com',
        phone: '+91 98765 43217',
        photoUrl: '/images/profiles/profile-4.jpg',
        githubUrl: 'https://github.com/devchauhan',
        linkedinUrl: 'https://linkedin.com/in/devchauhan',
        skills: [
            { name: 'Rust', description: 'Memory-safe systems programming and CLI tools.' },
            { name: 'Go', description: 'Concurrent backend services and networking tools.' },
            { name: 'Blockchain', description: 'Smart contracts with Solidity on Ethereum.' },
            { name: 'Linux', description: 'Kernel-level debugging and system administration.' },
        ],
        status: 'rejected',
        submittedAt: '2026-02-10T10:00:00Z',
        memberSince: '2025-06-15T00:00:00Z',
        department: 'Computer Science',
    },
    {
        id: 'dp7',
        name: 'Sanya Mehta',
        title: 'Backend Developer',
        email: 'sanya.mehta@gmail.com',
        phone: '+91 98765 43216',
        photoUrl: '/images/profiles/profile-5.jpg',
        githubUrl: 'https://github.com/sanyamehta',
        linkedinUrl: 'https://linkedin.com/in/sanyamehta',
        skills: [
            { name: 'JavaScript', description: 'Full-stack JS with modern ES6+ patterns.' },
            { name: 'Node.js', description: 'Express, NestJS, and real-time WebSocket servers.' },
            { name: 'MongoDB', description: 'Schema design, aggregation pipelines, and indexing.' },
            { name: 'GraphQL', description: 'Apollo Server for flexible API development.' },
        ],
        status: 'pending',
        submittedAt: '2026-02-25T10:00:00Z',
        memberSince: '2024-10-05T00:00:00Z',
        department: 'Information Technology',
    },
];
export const recentActivity = [
    { id: 'a1', type: 'message_received', message: 'New message from CodeForces Team', timestamp: '1 hour ago', actor: 'CodeForces Team' },
    { id: 'a2', type: 'profile_submitted', message: 'Sanya Mehta submitted profile for job pipeline', timestamp: '2 hours ago', actor: 'Sanya Mehta' },
    { id: 'a3', type: 'member_joined', message: 'Arjun Nair submitted a membership request', timestamp: '4 hours ago', actor: 'Arjun Nair' },
    { id: 'a4', type: 'post_published', message: 'Annual Hackathon 2026 Registration Open published', timestamp: '5 hours ago', actor: 'Ananya Sharma' },
    { id: 'a5', type: 'event_created', message: 'React Advanced Patterns Workshop created', timestamp: '1 day ago', actor: 'Meera Kapoor' },
    { id: 'a6', type: 'member_joined', message: 'Dev Chauhan membership approved', timestamp: '3 days ago', actor: 'Ananya Sharma' },
];
// ===== Contact Messages Data =====
export const demoContactMessages = [
    {
        id: 'cm1',
        name: 'Rahul Sharma',
        email: 'rahul.sharma@student.cu.edu',
        subject: 'How to join the club?',
        message: 'Hi, I am a first-year CS student and I am interested in joining CPCCU. Can you please guide me on the registration process and any prerequisites I need to fulfill?',
        status: 'unread',
        receivedAt: '2026-02-25T10:30:00Z',
    },
    {
        id: 'cm2',
        name: 'Dr. Amit Verma',
        email: 'amit.verma@cu.edu',
        subject: 'Workshop Collaboration Proposal',
        message: 'Dear CPCCU Team, I am a faculty member from the IT department. I would like to discuss a potential collaboration for conducting a joint workshop on Cloud Computing. Please let me know a convenient time to meet.',
        status: 'unread',
        receivedAt: '2026-02-24T14:15:00Z',
    },
    {
        id: 'cm3',
        name: 'Tech Solutions Inc.',
        email: 'hr@techsolutions.com',
        subject: 'Campus Recruitment Partnership',
        message: 'Hello, We are interested in recruiting talented developers from your club. We would like to discuss internship and full-time opportunities for your members. Please share the process for campus partnerships.',
        status: 'read',
        receivedAt: '2026-02-22T09:00:00Z',
    },
    {
        id: 'cm4',
        name: 'Sneha Patel',
        email: 'sneha.patel@gmail.com',
        subject: 'Event Sponsorship Inquiry',
        message: 'Hi Team, I represent a startup that would like to sponsor your upcoming hackathon. Can you share the sponsorship tiers and benefits? Looking forward to your response.',
        status: 'replied',
        receivedAt: '2026-02-20T16:45:00Z',
        repliedAt: '2026-02-21T10:00:00Z',
    },
    {
        id: 'cm5',
        name: 'Anonymous',
        email: 'feedback@example.com',
        subject: 'Feedback on last workshop',
        message: 'The React workshop was great but I think the pace was a bit too fast for beginners. It would be helpful to have more hands-on exercises.',
        status: 'archived',
        receivedAt: '2026-02-15T11:00:00Z',
    },
    {
        id: 'cm6',
        name: 'Priyanka Roy',
        email: 'priyanka.roy@student.cu.edu',
        subject: 'Certificate Issue',
        message: 'Hello, I participated in the Git workshop last month but have not received my participation certificate yet. My registration ID was GIT2026-045. Please help.',
        status: 'unread',
        receivedAt: '2026-02-26T08:20:00Z',
    },
    {
        id: 'cm7',
        name: 'CodeForces Team',
        email: 'partners@codeforces.com',
        subject: 'Official Contest Partnership',
        message: 'Dear CPCCU, We noticed your active participation in competitive programming contests. We would like to offer official partnership status for your club which includes exclusive contest hosting rights and prizes.',
        status: 'unread',
        receivedAt: '2026-02-26T06:00:00Z',
    },
];
// ===== Certificate Data =====
export const demoCertificates = [
    {
        id: 'cert1',
        certificateId: 'CPCCU-2026-001',
        recipientName: 'Rahul Roy Nipon',
        recipientStudentId: '2022-1-60-001',
        eventName: 'Beat the Champ CPCCU',
        placement: '3rd',
        issuedAt: '2026-04-19T00:00:00Z',
        verificationUrl: 'https://cpccu.club/verify/CPCCU-2026-001',
    },
    {
        id: 'cert2',
        certificateId: 'CPCCU-2026-002',
        recipientName: 'Imrul Hasan Rafi',
        recipientStudentId: '2022-1-60-042',
        eventName: 'Debugging Derby Again CPCCU',
        placement: '2nd',
        issuedAt: '2026-04-19T00:00:00Z',
        verificationUrl: 'https://cpccu.club/verify/CPCCU-2026-002',
    },
    {
        id: 'cert3',
        certificateId: 'CPCCU-2026-003',
        recipientName: 'MD. Tahsin Ferdous',
        recipientStudentId: '2021-2-60-015',
        eventName: 'CPCCU Contest 3',
        placement: '1st',
        issuedAt: '2026-04-19T00:00:00Z',
        verificationUrl: 'https://cpccu.club/verify/CPCCU-2026-003',
    },
    {
        id: 'cert4',
        certificateId: 'CPCCU-2026-004',
        recipientName: 'Naeem Biswass Niloy',
        recipientStudentId: '2023-1-60-089',
        eventName: 'CPCCU Contest 1',
        placement: '2nd',
        issuedAt: '2026-04-19T00:00:00Z',
        verificationUrl: 'https://cpccu.club/verify/CPCCU-2026-004',
    },
    {
        id: 'cert5',
        certificateId: 'CPCCU-2026-005',
        recipientName: 'Naeem Biswass Niloy',
        recipientStudentId: '2023-1-60-089',
        eventName: 'Eid Code Fest CPCCU: 2024',
        placement: '1st',
        issuedAt: '2026-04-19T00:00:00Z',
        verificationUrl: 'https://cpccu.club/verify/CPCCU-2026-005',
    },
    {
        id: 'cert6',
        certificateId: 'CPCCU-2026-006',
        recipientName: 'Anisur Rahman Farazi',
        recipientStudentId: '2022-1-60-017',
        eventName: 'CP Bootcamp 2026',
        placement: 'completion',
        issuedAt: '2026-03-15T00:00:00Z',
        verificationUrl: 'https://cpccu.club/verify/CPCCU-2026-006',
    },
];
// ===== Contributor Data =====
export const demoContributors = [
    {
        id: 'c1',
        username: 'mdsiaofficial',
        name: 'MD Sia Official',
        avatarUrl: '/images/profiles/profile-2.jpg',
        githubUrl: 'https://github.com/mdsiaofficial',
        linkedinUrl: 'https://linkedin.com/in/mdsiaofficial',
        commits: 186,
        role: 'Lead Developer',
        joinedAt: '2024-01-15T00:00:00Z',
    },
    {
        id: 'c2',
        username: 'anisurrahmanfarazi17',
        name: 'Anisur Rahman Farazi',
        avatarUrl: '/images/profiles/profile-4.jpg',
        githubUrl: 'https://github.com/anisurrahmanfarazi17',
        linkedinUrl: 'https://linkedin.com/in/anisurfarazi',
        commits: 178,
        role: 'Full Stack Developer',
        joinedAt: '2024-01-20T00:00:00Z',
    },
    {
        id: 'c3',
        username: 'rahulroynipon',
        name: 'Rahul Roy Nipon',
        avatarUrl: '/images/profiles/profile-6.jpg',
        githubUrl: 'https://github.com/rahulroynipon',
        linkedinUrl: 'https://linkedin.com/in/rahulroynipon',
        commits: 95,
        role: 'Backend Developer',
        joinedAt: '2024-02-10T00:00:00Z',
    },
    {
        id: 'c4',
        username: 'Abraralvi2002',
        name: 'Abrar Alvi',
        avatarUrl: '/images/profiles/profile-4.jpg',
        githubUrl: 'https://github.com/Abraralvi2002',
        commits: 15,
        role: 'Frontend Developer',
        joinedAt: '2024-06-01T00:00:00Z',
    },
    {
        id: 'c5',
        username: 'Md-Masum-Hossain',
        name: 'Md. Masum Hossain',
        avatarUrl: '/images/profiles/profile-2.jpg',
        githubUrl: 'https://github.com/Md-Masum-Hossain',
        linkedinUrl: 'https://linkedin.com/in/mdmasumhossain',
        commits: 14,
        role: 'Full Stack Developer',
        joinedAt: '2024-06-15T00:00:00Z',
    },
    {
        id: 'c6',
        username: 'Anik-36',
        name: 'Anik',
        avatarUrl: '/images/profiles/profile-4.jpg',
        githubUrl: 'https://github.com/Anik-36',
        commits: 12,
        role: 'UI Developer',
        joinedAt: '2024-07-01T00:00:00Z',
    },
];
// ===== Donator Data =====
export const demoDonators = [
    {
        id: 'd1',
        name: 'Zubayer Bin Ayub',
        avatarUrl: '/images/profiles/profile-2.jpg',
        contribution: 'Website Renewal Fee Contribution',
        amount: 500,
        donatedAt: '2026-03-01T00:00:00Z',
        isAnonymous: false,
    },
    {
        id: 'd2',
        name: 'Reduan Rafi',
        avatarUrl: '/images/profiles/profile-4.jpg',
        contribution: 'Website Renewal Fee Contribution',
        amount: 500,
        donatedAt: '2026-03-01T00:00:00Z',
        isAnonymous: false,
    },
    {
        id: 'd3',
        name: 'Kazi Ashraf Hossain',
        avatarUrl: '/images/profiles/profile-6.jpg',
        contribution: 'Website Renewal Fee Contribution',
        amount: 500,
        donatedAt: '2026-03-01T00:00:00Z',
        isAnonymous: false,
    },
    {
        id: 'd4',
        name: 'Md Omar Faruq',
        avatarUrl: '/images/profiles/profile-2.jpg',
        contribution: 'Website Renewal Fee Contribution',
        amount: 500,
        donatedAt: '2026-03-02T00:00:00Z',
        isAnonymous: false,
    },
    {
        id: 'd5',
        name: 'Mehedi Azad',
        avatarUrl: '/images/profiles/profile-4.jpg',
        contribution: 'Contest Prize Sponsorship',
        amount: 2000,
        donatedAt: '2026-02-15T00:00:00Z',
        isAnonymous: false,
    },
    {
        id: 'd6',
        name: 'Anonymous Donor',
        avatarUrl: '',
        contribution: 'General Support',
        amount: 1000,
        donatedAt: '2026-02-01T00:00:00Z',
        isAnonymous: true,
    },
];
// ===== Site Statistics =====
export const siteStatistics = {
    members: 248,
    photos: 156,
    events: 32,
    awards: 48,
    totalVisitors: 659,
    certificatesIssued: 64,
    contestsHeld: 19,
    winnersRecognized: 36,
};
