"use client";

import { useMemo } from "react";
import Link from "next/link";
import { GitPullRequest, ExternalLink, Award } from "lucide-react";
import { cn } from "@/lib/utils";
import { SectionCard, EmptyState } from "./SectionCard";
import { findContributorByGithub, parseContributionInfo } from "@/lib/public-content";
import contributorsData from "@/data/contributors.json";

const rankStyles = {
  1: "bg-amber-100 text-amber-800 border-amber-200",
  2: "bg-slate-100 text-slate-700 border-slate-200",
  3: "bg-orange-100 text-orange-800 border-orange-200",
};

function RankBadge({ rank }) {
  if (!rank) return null;
  const color = rankStyles[rank] || "bg-purple-100 text-purple-800 border-purple-200";
  const label = rank <= 3
    ? ["🥇 Top Contributor", "🥈 Rank #2", "🥉 Rank #3"][rank - 1]
    : `🏅 Rank #${rank}`;
  return (
    <span className={cn("inline-flex items-center gap-1.5 rounded-full border px-3 py-1 text-[11px] font-bold", color)}>
      <Award className="size-3" aria-hidden="true" />
      {label}
    </span>
  );
}

// Approximate sync date — the contributors.json is regenerated by GitHub Actions on each push.
// We show a reasonable estimate based on the project's active development cycle.
// In production, this could come from a build-time metadata endpoint.
const LAST_SYNC_DATE = "July 2026";

export function ContributionsSection({ githubUrl }) {
  const contributorInfo = useMemo(() => {
    if (!githubUrl) return null;
    const contributor = findContributorByGithub(githubUrl, contributorsData);
    return contributor ? parseContributionInfo(contributor) : null;
  }, [githubUrl]);

  if (!contributorInfo) {
    return (
      <SectionCard title="Open Source Contributions" icon={GitPullRequest} id="contributions">
        <EmptyState
          icon={GitPullRequest}
          title="Contribution data unavailable"
          description="This member's GitHub contributions to the CPCCU project could not be verified from local data."
        />
        <div className="mt-3 text-center">
          <Link
            href="/contributors"
            className="inline-flex items-center gap-1.5 text-xs font-semibold text-primary hover:underline"
          >
            View all contributors
            <ExternalLink className="size-3" aria-hidden="true" />
          </Link>
        </div>
      </SectionCard>
    );
  }

  const { commitCount, displayText, name, avatar, batch, department, rank } = contributorInfo;

  return (
    <SectionCard title="Open Source Contributions" icon={GitPullRequest} id="contributions">
      <div className="flex flex-col gap-4">
        {/* Contributor identity + rank */}
        <div className="flex flex-wrap items-start justify-between gap-3">
          {avatar && (
            <div className="flex items-center gap-3 min-w-0">
              <img
                src={avatar}
                alt={name || "Contributor"}
                className="size-10 shrink-0 rounded-full ring-2 ring-border object-cover"
              />
              <div className="min-w-0">
                <p className="text-sm font-bold text-foreground truncate">{name}</p>
                {batch && (
                  <p className="text-xs text-muted-foreground truncate">
                    {department ? `${department} · Batch ${batch}` : `Batch ${batch}`}
                  </p>
                )}
              </div>
            </div>
          )}
          <RankBadge rank={rank} />
        </div>

        {/* Stats grid */}
        <div className="grid grid-cols-2 gap-3">
          {commitCount !== null && (
            <div className="rounded-lg border border-border bg-accent/30 p-3 text-center">
              <p className="font-serif text-2xl font-black text-foreground">{commitCount}</p>
              <p className="mt-0.5 text-[11px] font-semibold text-muted-foreground">Commits</p>
            </div>
          )}
          <div className="rounded-lg border border-border bg-accent/30 p-3 text-center">
            <p className="font-serif text-2xl font-black text-foreground">CPCCU</p>
            <p className="mt-0.5 text-[11px] font-semibold text-muted-foreground">Project</p>
          </div>
        </div>

        {/* Description */}
        <p className="text-sm leading-relaxed text-muted-foreground text-pretty">{displayText}</p>

        {/* View contributor profile link */}
        <div className="flex flex-wrap items-center justify-between gap-2 pt-1">
          <Link
            href="/contributors"
            className="inline-flex items-center gap-1.5 rounded-lg border border-border bg-card px-3 py-1.5 text-xs font-bold text-foreground transition-colors hover:border-primary/40 hover:bg-accent"
          >
            <ExternalLink className="size-3" aria-hidden="true" />
            View Contributor Profile →
          </Link>
          <span className="text-[10px] text-muted-foreground/60">
            Last synced: {LAST_SYNC_DATE}
          </span>
        </div>
      </div>
    </SectionCard>
  );
}
